### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by graaff** [flori/spruz#1]
I'm currently looking to add spruz to Gentoo since it is an indirect dependency of Passenger 3.0.0, but unfortunately there is no licensing information in your package. Could you please decide on a license and add this to the distribution so that we can add the package with the proper licensing?

**Comment by flori** [comment]
The latest version 0.2.0 is now licensed with the X11 (MIT) license.

See this commit:
flori/spruz@ff4b5e055784ae755fdb0bd6784e4e370d4c0cbf

**Comment by graaff** [comment]
Thanks! I've now added spruz to Gentoo.
